### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by semalis**
Added a link to a telegram bot that monitors missed validator blocks and sends notifications

### CODE REVIEW

**Review by semalis — COMMENTED** [review]
Added a link to a telegram bot that monitors missed validator blocks and sends notifications

**Comment by ccamel** [comment]
@amimart ping.

**Review by amimart — APPROVED** [review]
👍

**Review by ccamel — APPROVED** [review]
Lgtm! Thanks for your contribution :heart:

**Comment by ccamel** [comment]
Merged https://github.com/okp4/awesome/commit/b4e0c5272651f3ed97443d44f27c10855aced2ca.

**Pull request closed without merging**
