### PR TITLE
style: add social media icons and update readme

### PR DESCRIPTION
**Pull request by jeremylgn**
Self explanatory.

image

### CODE REVIEW

**Review by ccamel — APPROVED** [review]
That's cute! 😍

**Review by fredericvilcot — APPROVED** [review]
Great! 😊

**Review by SonnevilleDamien — APPROVED** [review]
Great 🫶🏼

**Review by bdeneux — APPROVED** [review]
👩‍🎨 Nice

**Review by amimart — APPROVED** [review]

**Review by ManonPoint26 — APPROVED** [review]

**Comment by ManonPoint26** [comment]
Approved by the queen Manonita ;)

**Pull request merged**
